install:
	rm -rf ~/.zshrc ~/.oh-my-zsh
	ln -s `pwd`/zshrc ~/.zshrc
	ln -s `pwd`/oh-my-zsh ~/.oh-my-zsh
	cd ~/.oh-my-zsh/custom/plugins/ && git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
	cd ~/.oh-my-zsh/custom/plugins/ && git clone https://github.com/zsh-users/zsh-completions
